Do not run pre-commit action on windows
For some reason the pre-commit action fails on the windows-latest
runner:

  Run pre-commit/action@v2.0.3
  install pre-commit
  Error: The process 'C:\hostedtoolcache\windows\Python\3.10.1\x64\Scripts\pip.exe' failed with exit code 3221225477

Since the pre-commit output will be identical on all systems anyway, I
am moving the pre-commit test to a separate job that only runs on
ubuntu-latest.